/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Week11RouteImport } from './routes/week-11'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Week11Route = Week11RouteImport.update({
  id: '/week-11',
  path: '/week-11',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/week-11': typeof Week11Route
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/week-11': typeof Week11Route
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/week-11': typeof Week11Route
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/week-11' | '/api/tasks' | '/api/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/week-11' | '/api/tasks' | '/api/tasks/$id'
  id: '__root__' | '/' | '/week-11' | '/api/tasks' | '/api/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Week11Route: typeof Week11Route
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week-11': {
      id: '/week-11'
      path: '/week-11'
      fullPath: '/week-11'
      preLoaderRoute: typeof Week11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
  }
}

interface ApiTasksRouteChildren {
  ApiTasksIdRoute: typeof ApiTasksIdRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksIdRoute: ApiTasksIdRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Week11Route: Week11Route,
  ApiTasksRoute: ApiTasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
